### ISSUE TITLE
Allow everything except <script>?

### ISSUE THREAD

**Issue by aralroca** [bevacqua/insane#22]
Is there any way to say that I accept EVERYTHING except something specific? I am interested in being able to put any kind of class, tag, etc. Except the <script> tag everything else yes.

Thank you very much

**Comment by samber** [comment]
This is probably not a best practice.

You should blacklist everything except a few tags/attributes.

For example, scripts can be executed from a `<a>` tag

**Comment by aralroca** [comment]
Okay, you're right @samber. I close the issue. Thanks anyway.
